deewhy-webservice:
  build: .
  depends_on:
    - deewhy-cassandra
  environment:
    CASSANDRA_HOST=deewhy-cassandra
  ports:
    - "5000:5000"
  links:
    - deewhy-cassandra

deewhy-cassandra:
  image: cassandra:3.11.7